steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - cloud_function_handler
      - --runtime
      - python39
      - --source=./cloud_function
      - --trigger-bucket
      - gs://vinxu-cb-bucket
      - --region=europe-west1