steps:

  # Construir la imagen del contenedor
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/the-bridge-cloud-388610/cb_app:1.0', './cloud_run']

  # Subir la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/the-bridge-cloud-388610/cb_app:1.0']

  # Desplegar la imagen en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - run
    - deploy
    - cbapp
    - --image=gcr.io/the-bridge-cloud-388610/cb_app:1.0
    - --region=europe-west1
    - --platform=managed
    - --allow-unauthenticated
    - --port=5000
